### ISSUE TITLE
Activity diagram metrics not showing(NaN for last 4 metrics)

### ISSUE THREAD

**Issue by mhshahbazi** [mhamiri96/Model-refactor#3]
After running the final project, by standard configuration result contains unwanted values. Activity diagram metrics are not showing correctly. Fore more information config data will be mentioned:
![Untitled](https://user-images.githubusercontent.com/14026788/215278770-800ddae8-9bdb-48b2-b640-adfbdedc49b0.png)

Number of Objectives : 11

Considered Objectives :  Coupling Cohesion Complxity Sability Standard Deviation Encapsulation Interfacing Average Of Parameters Methods Average Of Number of Edges Average Of Number of Actions Average Of Locality 

Population size : 100

Iterations : 3.0

Sigma : 1.0

Reference Point :  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 

Pareto size : 100

Average number of fronts : 1.6666666666666667

Selected solutions number (optional) : 2.0

Selected solutions are the set of best solution (minimal distance) in each iteration (duplicated solutions removed)

**Comment by mhamiri96** [comment]
it seems we got problem in our activity metrics which can be caused by not calculated properly. @MasoudRabiee should check it on.

**Comment by MasoudRabiee** [comment]
i add commits for fix this bug. you can see and check new result files.
